repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8==6.0.0]
        language_version: python3.9
        exclude: ^src/app/alembic
        files: ^src/

  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        args: [--ignore, DL3008, --ignore , DL3007, --ignore, DL4006]
        exclude: ^src/app/alembic

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args:
          - --exclude=SC2046
          - --exclude=SC2006
        exclude: ^src/app/alembic